version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "API"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-d429jxgbjsux"
s3_prefix = "API"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["InferenceFunction=042646676730.dkr.ecr.us-east-1.amazonaws.com/apidb974238/inferencefunction7c73919drepo"]
